spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/car_history
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    url: jdbc:postgresql://localhost:5432/car_history
    user: postgres
    password: postgres
    baseline-on-migrate: true

logging:
  level:
    org.springframework: INFO
    sql: debug